version: '3.8'
services:
  zs_ssl_recon2025:
    build: 
      context: .
      dockerfile: Docker/Dockerfile
    container_name: zs_ssl_recon2025
    tty: true
    volumes:
      - ".:/workdir"
    shm_size: '8gb'
    deploy:
      resources:
        reservations:
          devices:
           - driver: nvidia
             device_ids: ['0']
             capabilities: [utility, compute, video]


