version: '3.8'
services:
  zs_ssl_recon2025:
    build: 
      context: .
      dockerfile: Docker/Dockerfile
    container_name: zs_ssl_recon2025
    tty: true
    volumes:
      - ".:/workdir"
    shm_size: '8gb'
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
           - driver: nvidia
             device_ids: ['0']
             capabilities: [utility, compute, video]
    working_dir: /workdir
    entrypoint: >
      sh -c "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''"


