FROM nvcr.io/nvidia/pytorch:23.07-py3

RUN pip install jupyter jupyterlab

RUN pip install h5py==3.9.0

RUN pip install pytorch-lightning==2.0.6 torchsummary==1.5.1

RUN pip install datetime

RUN pip install torch